test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Cloudflare R2 Storage configuration (Production)
cloudflare:
  service: S3
  endpoint: https://<%= ENV['CLOUDFLARE_ACCOUNT_ID'] %>.r2.cloudflarestorage.com
  access_key_id: <%= ENV['CLOUDFLARE_R2_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['CLOUDFLARE_R2_SECRET_ACCESS_KEY'] %>
  region: auto
  bucket: <%= ENV['CLOUDFLARE_R2_BUCKET'] || 'ridecycle-production' %>
  public: true
  # Rails 7 enhancements for Active Storage
  cache_control: "public, max-age=3600"

# AWS S3 Storage configuration (Legacy/Backup)
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] || 'ap-northeast-1' %>
  bucket: <%= ENV['AWS_S3_BUCKET_NAME'] || 'ride-cycle-production' %>
  public: true
  # Rails 7 enhancements for Active Storage
  cache_control: "public, max-age=3600"
  
# Development S3 configuration
amazon_dev:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] || 'ap-northeast-1' %>
  bucket: <%= ENV['AWS_S3_DEV_BUCKET_NAME'] || 'ride-cycle-development' %>
  public: true
  cache_control: "public, max-age=1800"
# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
